In [31]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [32]:
df = pd.read_csv('../Video_games_esrb_rating.csv')

In [33]:
df.drop(['title'], inplace=True, axis=1)

In [34]:
ratings = df['esrb_rating'].unique()
ratings

array(['E', 'ET', 'M', 'T'], dtype=object)

In [35]:
df['esrb_rating'] = df['esrb_rating'].replace(
    'E', 0).replace('ET', 1).replace('T', 2).replace('M', 3)

In [36]:
y = df['esrb_rating']
X = df.drop(['esrb_rating'], axis=1)

In [37]:
SEED = 42
X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    test_size=0.2,
                                                    random_state=SEED)

In [38]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier()
classifier.fit(X_train, y_train)

DecisionTreeClassifier()

In [39]:
y_pred = classifier.predict(X_test)

In [40]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[ 96   2   1   0]
 [  4  49   8   0]
 [  2  19 117   8]
 [  0   0  14  59]]
              precision    recall  f1-score   support

           0       0.94      0.97      0.96        99
           1       0.70      0.80      0.75        61
           2       0.84      0.80      0.82       146
           3       0.88      0.81      0.84        73

    accuracy                           0.85       379
   macro avg       0.84      0.85      0.84       379
weighted avg       0.85      0.85      0.85       379

